version: '3.7'

services:
  app:
    image: ruby:3.0.2
    volumes:
      - .:/app
    working_dir: /app
    command: bash
    environment:
      BUNDLE_PATH: /app/.gems
      MEMCACHE_SERVERS: "memcached:11211"
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
